### PR TITLE
fix: use regex to avoid falsely replacing ports starting with 80

### LINKED ISSUE #120: BaseURL incorrectly modified : ENOTFOUND localhost81
### Version

[v0.5.10](https://github.com/http/releases/tag/v0.5.10)

### Reproduction link

[https://jsfiddle.net/Lqrzf41m/](https://jsfiddle.net/Lqrzf41m/)

### Steps to reproduce

I'm just using the module, in a empty `nuxtServerInit` action.

My baseURL is http://localhost:8081

```js
async nuxtServerInit({ commit }, context) {
    try {
      const libs = await context.$http.$get('/api/libs/')
      commit('setLibs', libs)
    } catch (error) {
      console.error(error)
    }
}
```

### What is expected ?

`this.$http` to use a valid baseURL.

### What is actually happening?

ERROR  request to http://localhost81/api/libs/ failed, reason: getaddrinfo ENOTFOUND localhost81

### Additional comments?

Looks like this line causes the issue : https://github.com/nuxt/http/blob/dev/lib/module.js#L119https://github.com/nuxt/http/blob/dev/lib/module.js#L119

Manualy setting http.baseURL in nuxt config produces the same error.

### Workaround

Use a port not starting by `80`

### PR DESCRIPTION
**Pull request by azrikahar**
This PR fixes #120.

## Problem Statement

Following what the issue addresses, the following logic is currently used to remove `:80` when the baseURL starts with `http://`.

https://github.com/nuxt/http/blob/c002aaa97c45fa5dfd91325a005fd5cc18a55b57/lib/module.js#L117-L120

However, this logic will also be true for ANY ports that starts with `:80`, such as `:8081`, `:8000` and so on since they do technically contain `:80` in them.

## PR Fix

We can use the regex `/^http:\/\/.*:80$/` to make the check stricter, which requires the baseURL to fulfill all the following conditions:
- **Starts with `http://`** (`^http:\/\/` : `^` means "start of line" and we need to escape `/` into `\/`)
- contains whatever characters in between (`.*`: `.` means any character and `*` means appearing zero or more times)
- **Ends with `:80` only** (`:80$`: `$` means "end of line")

### Test Case 1 - baseURL ends with :80

chrome_BpMxhForHB

Both logic works as intended.

### Test Case 2 - baseURL ends with :8081

chrome_A6KRw1HBEe

Here we can see the original logic falsely turns `http://localhost:8081` to `http://localhost81` (as reported by the issue) whereas the regex logic will not trigger as intended.

### CODE REVIEW

**Comment by azrikahar** [comment]
I was hesitant at first, but I double checked and noticed the test cases includes a trailing slash to the baseURL here:

https://github.com/nuxt/http/blob/c002aaa97c45fa5dfd91325a005fd5cc18a55b57/test/defaults.test.js#L11

So I added another commit that checks for this as well since my original regex will fail for baseURLs with trailing slash.

## Original Regex

`/^http:\/\/.*:80$/`

## New Regex

`/^http:\/\/.*:80\/?$/`

The `\/?` means the forward slash `\/` can occur once or zero times, as indicated by the `?`. Sorry for not double checking before making the initial PR.

**Comment by pi0** [comment]
Hi @azrikahar thanks for PR and nice explanations. I think we only have one issue with current regex which is when baseURL also has a path like (`http://foo.com:80/foo`) `/^http:\/\/.*:80\/?$/.test('http://foo.com:80/foo')` does not matches for replace. So `/^http:\/\/.*:80\/|^http:\/\/.*:80$/` would do the trick (or if you have better idea)

**Comment by azrikahar** [comment]
@pi0 thank you for the review :) Can't believe that scenario slipped my mind 🤦‍♂️

From my understanding, `/^http:\/\/.*:80\/|^http:\/\/.*:80$/` means either it is `:80/(anything or empty)` or ends with `:80` right? I believe we can shorten it to `/^http:\/\/.*:80(\/|$)/` (which just uses your `|` and shorten it).

Definitely not super experienced in regex so here's additional tests for you to review in case I still miss anything.

## Test code

<details>
<summary>Click to toggle source code</summary>

```js
const baseUrls = [
  'http://foo.com:80',
  'http://foo.com:8080',
  'http://foo.com:80/',
  'http://foo.com:8080/',
  'http://foo.com:80/foo',
  'http://foo.com:8080/foo',
]

const rg = /^http:\/\/.*:80(\/|$)/

baseUrls.forEach(baseUrl => {
  console.log('before:', baseUrl)
  console.log('after: ', rg.test(baseUrl) ? baseUrl.replace(':80', '') : baseUrl)
  console.log('---')
})
```
</details>


## Test result

chrome_go8KIMgov2

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks for investigation @azrikahar <3 I merged with `/^http:\/\/.*:80(\/|$)/` seems perfect!

**Pull request merged**
